book-service:
  servers:
  - url: http://localhost:8080/
    enabled: true
    zone: US
  - url: http://localhost:8081/
    enabled: true
    zone: Europe
  - url: http://localhost:8085/
    enabled: true
    zone: Europe

retry-config:
  max-retries: 3
  delay: 1
  max-duration: 30

order-service:
  zone: Europe

server:
  port: 9500

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  cache:
    caffeine:
      spec: initialCapacity=100, maximumSize=20000, expireAfterWrite=10s

  profiles:
    active: cpu-utilization
