book-service:
  servers:
  - url: http://localhost:8080/
    enabled: true
  - url: http://localhost:8085/
    enabled: true

server:
  port: 9000
management:
  endpoint:
    health:
      show-details: always
